### ISSUE TITLE
vue3+vite4，开发环境获取的源码行数是正确的，但是打包后生产环境源码行数不正确

### ISSUE THREAD

**Issue by YWJ-hy** [baozouai/vite-plugin-enhance-log#10]
开发环境获取的源码行数是正确的，但是打包后生产环境源码行数不正确

**Comment by YWJ-hy** [comment]
.ts文件正常，.vue文件生产环境源码行数不对

**Comment by baozouai** [comment]
> .ts文件正常，.vue文件生产环境源码行数不对

@YWJ-hy 看下是不是其他插件没生成sourcemap，见https://github.com/baozouai/vite-plugin-enhance-log/issues/2

**Comment by YWJ-hy** [comment]
删除只剩下@vitejs/plugin-vue和@vitejs/plugin-vue-jsx两个插件，打包出来还是一样行数不对

**Comment by YWJ-hy** [comment]
> > .ts文件正常，.vue文件生产环境源码行数不对
> 
> @YWJ-hy 看下是不是其他插件没生成sourcemap，见#2

删除只剩下@vitejs/plugin-vue和@vitejs/plugin-vue-jsx两个插件，打包出来还是一样行数不对

**Comment by YWJ-hy** [comment]
发现问题了，因为我设置了esbuild.pure，删除了部分console.log，有没有办法解决？

**Comment by baozouai** [comment]
> 发现问题了，因为我设置了esbuild.pure，删除了部分console.log，有没有办法解决？

暂时没研究esbuild的，你先去掉吧，或者给个最小demo复现

**Comment by YWJ-hy** [comment]
> > 发现问题了，因为我设置了esbuild.pure，删除了部分console.log，有没有办法解决？
> 
> 暂时没研究esbuild的，你先去掉吧，或者给个最小demo复现

不好意思，我搞错了，不是esbuild的问题，是因为打包没有生成sourcemap导致的，我在build时生成sourcemap就正常了
<img width="514" alt="image" src="https://github.com/baozouai/vite-plugin-enhance-log/assets/48192638/9e80bce9-9728-4e57-9d33-853f81e9ad5a">

**Comment by baozouai** [comment]
> > > 发现问题了，因为我设置了esbuild.pure，删除了部分console.log，有没有办法解决？
> > 
> > 
> > 暂时没研究esbuild的，你先去掉吧，或者给个最小demo复现
> 
> 不好意思，我搞错了，不是esbuild的问题，是因为打包没有生成sourcemap导致的，我在build时生成sourcemap就正常了 <img alt="image" width="514" src="https://private-user-images.githubusercontent.com/48192638/332481699-9e80bce9-9728-4e57-9d33-853f81e9ad5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzY5MjEsIm5iZiI6MTcxNjMzNjYyMSwicGF0aCI6Ii80ODE5MjYzOC8zMzI0ODE2OTktOWU4MGJjZTktOTcyOC00ZTU3LTlkMzMtODUzZjgxZTlhZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAwMTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZWZlNGFlMTQ1ZjFkZDA2NWI4MzRmZDU2YWQ0ZTM2ODM1ZjZkMzYwYzhmZWM3NWQxYTI5N2EyYzA5NzFlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VtU-Y9EyIKNp3W7xmylElYIdaOmvMMHf6MBQkUKkJ34">

啊这，我以为是开发阶段。。没问题就行
