### ISSUE TITLE
如果项目中使用了 vite-plugin-vue-setup-extend 插件，log出来的行数是null

### ISSUE THREAD

**Issue by uli45** [baozouai/vite-plugin-enhance-log#2]
<img width="525" alt="image" src="https://github.com/baozouai/vite-plugin-enhance-log/assets/78719805/94e9517c-42fa-4989-b5e8-9c8378629f23">

**Comment by uli45** [comment]
不使用vite-plugin-vue-setup-extend 插件就能正常显示 
<img width="637" alt="image" src="https://github.com/baozouai/vite-plugin-enhance-log/assets/78719805/a461c76e-bb47-4f8f-be68-da534461620e">

**Comment by baozouai** [comment]
> 不使用vite-plugin-vue-setup-extend 插件就能正常显示 <img alt="image" width="637" src="https://user-images.githubusercontent.com/78719805/277598744-a461c76e-bb47-4f8f-be68-da534461620e.png">

@uli45 不是我的问题哦，是因为你使用那个插件生成sourcemap没有指定source，见https://github.com/vbenjs/vite-plugin-vue-setup-extend/blob/main/packages/core/src/lib.ts#L24，其实你可以debugger，会发现控制台不是定位到源码，原因就在于sourcemap的问题，如：

<img width="707" alt="image" src="https://github.com/baozouai/vite-plugin-enhance-log/assets/33510001/d6773617-cd8d-4eaf-8b33-2a6d03673f7c">
但控制台却是这样的：
<img width="606" alt="image" src="https://github.com/baozouai/vite-plugin-enhance-log/assets/33510001/ab62b0c6-c395-4e4e-b112-f80c956b49c0">


这样才是对的：

<img width="831" alt="image" src="https://github.com/baozouai/vite-plugin-enhance-log/assets/33510001/33e89a82-fbe2-47f4-ac83-39c9393c05bc">

**Comment by baozouai** [comment]
> 不使用vite-plugin-vue-setup-extend 插件就能正常显示 <img alt="image" width="637" src="https://user-images.githubusercontent.com/78719805/277598744-a461c76e-bb47-4f8f-be68-da534461620e.png">

推荐使用vite-plugin-vue-setup-extend-plus
见issue https://github.com/vbenjs/vite-plugin-vue-setup-extend/issues/11
