### ISSUE TITLE
行数显示为null

### ISSUE THREAD

**Issue by Bob0411** [baozouai/vite-plugin-enhance-log#3]
vite: 5.0.2
vue：3.3

附件：
![bug](https://github.com/baozouai/vite-plugin-enhance-log/assets/46805190/812dfabb-ced9-4490-858f-f3f26645c843)

**Comment by baozouai** [comment]
> vite: 5.0.2 vue：3.3
> 
> 附件： ![bug](https://user-images.githubusercontent.com/46805190/284925699-812dfabb-ced9-4490-858f-f3f26645c843.png)

看下你是不是用了其他插件导致sourcemap丢失，从而无法拿到行数

见：[https://github.com/baozouai/vite-plugin-enhance-log/issues/2](url) 

@Bob0411
