### ISSUE TITLE
解构的log如何识别

### ISSUE THREAD

**Issue by YWJ-hy** [baozouai/vite-plugin-enhance-log#9]
const { log } = console;
log("111")

这种如何识别呢

**Comment by baozouai** [comment]
> const { log } = console; log("111")
> 
> 这种如何识别呢

可以看下logMethodReg，https://github.com/baozouai/vite-plugin-enhance-log/blob/master/src/index.ts#L49

https://github.com/baozouai/vite-plugin-enhance-log#%EF%B8%8F-options

**Comment by YWJ-hy** [comment]
> > const { log } = console; log("111")
> > 这种如何识别呢
> 
> 可以看下logMethodReg，https://github.com/baozouai/vite-plugin-enhance-log/blob/master/src/index.ts#L49
> 
> https://github.com/baozouai/vite-plugin-enhance-log#%EF%B8%8F-options

不行吧，CallExpression是遍历的函数调用，也就是上面解构出来的log，不能直接匹配"log"，怕误判，好像不好处理

**Comment by baozouai** [comment]
> > > const { log } = console; log("111")
> > > 这种如何识别呢
> > 
> > 
> > 可以看下logMethodReg，[`master`/src/index.ts#L49](https://github.com/baozouai/vite-plugin-enhance-log/blob/master/src/index.ts?rgh-link-date=2024-05-06T15%3A22%3A18Z#L49)
> > [baozouai/vite-plugin-enhance-log#%EF%B8%8F-options](https://github.com/baozouai/vite-plugin-enhance-log#%EF%B8%8F-options)
> 
> 不行吧，CallExpression是遍历的函数调用，也就是上面解构出来的log，不能直接匹配"log"，怕误判，好像不好处理

那就不行，你别结构呗
